server:
  port:8090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/chenxin?statementInterceptors=com/learningRoad/Interceptor/JdbcInterceptor.java

mybatis:
  mapper-locations: classpath:mapper/*.xml

